name: todoapp
description: A simple ToDo App using Google Firebase

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  animated_text_kit: ^2.5.4
  cloud_firestore: ^0.14.3
  firebase_core: ^0.5.2
  firebase_auth: ^0.18.3
  modal_progress_hud: ^0.1.3
  alert_dialog: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/


  fonts:
    - family: BigShoulders
      fonts:
        - asset: fonts/BigShouldersInlineText-Black.ttf

    - family: Modak
      fonts:
        - asset: fonts/Modak-Regular.ttf

    - family: Handlee
      fonts:
        - asset: fonts/Handlee-Regular.ttf
